"""
train_gnn.py
────────────
Train a GraphSAGE model on the synthetic cloud infrastructure graph.

Pipeline:
  1. Load data/graph_data.pt (generated by data_generator.py)
  2. Import GraphSAGE from Python-Backend
  3. Train for 200 epochs — Adam(lr=0.01), BCELoss
  4. Print loss every 20 epochs
  5. Evaluate (accuracy + F1) on the full graph
  6. Save state dict to models/gnn_model.pt
  7. Plot & save training loss curve to reports/training_loss.png

Usage:
  cd ML
  python train_gnn.py
"""

import os
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import sys
import time
import torch
import torch.nn as nn
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

# ── Allow importing from Python-Backend ──────────────────────────────────────
_script_dir   = os.path.dirname(os.path.abspath(__file__))
_backend_root = os.path.join(_script_dir, "..", "Python-Backend")
sys.path.insert(0, _backend_root)

from app.services.gnn_model import GraphSAGE   # noqa: E402

# ─── Config ───────────────────────────────────────────────────────────────────
DATA_PATH    = os.path.join(_script_dir, "data", "graph_data.pt")
MODEL_DIR    = os.path.join(_script_dir, "models")
REPORT_DIR   = os.path.join(_script_dir, "reports")
MODEL_PATH   = os.path.join(MODEL_DIR, "gnn_model.pt")
LOSS_PLOT    = os.path.join(REPORT_DIR, "training_loss.png")

EPOCHS       = 200
LR           = 0.01
PRINT_EVERY  = 20
THRESHOLD    = 0.5
INPUT_DIM    = 5      # 5 features per node
SEED         = 42


def set_seed(seed: int):
    torch.manual_seed(seed)
    np.random.seed(seed)


def load_data(path: str):
    if not os.path.exists(path):
        print(f"\n❌  Data file not found: {path}")
        print("    Run `python data_generator.py` first.\n")
        sys.exit(1)
    data = torch.load(path)
    print(f"✅  Loaded graph: {data.num_nodes} nodes, "
          f"{data.edge_index.size(1)} edges, "
          f"{int(data.y.sum())} anomalies")
    return data


def train_epoch(model, data, optimizer, criterion):
    model.train()
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)      # [N, 1]
    loss = criterion(out.squeeze(1), data.y.float())
    loss.backward()
    optimizer.step()
    return loss.item()


@torch.no_grad()
def evaluate(model, data, threshold=THRESHOLD):
    model.eval()
    out    = model(data.x, data.edge_index).squeeze(1)   # [N]
    preds  = (out >= threshold).long().cpu().numpy()
    labels = data.y.cpu().numpy()
    acc    = accuracy_score(labels, preds)
    f1     = f1_score(labels, preds, zero_division=0)
    return acc, f1, out.cpu().numpy()


def plot_loss(losses: list, save_path: str):
    """Save training loss curve. Skips silently if matplotlib unavailable."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        epochs = list(range(1, len(losses) + 1))

        fig, ax = plt.subplots(figsize=(8, 4))
        ax.plot(epochs, losses, color="#6366f1", linewidth=2, label="BCELoss")
        ax.fill_between(epochs, losses, alpha=0.08, color="#6366f1")

        ax.set_xlabel("Epoch",    color="white", fontsize=11)
        ax.set_ylabel("BCELoss",  color="white", fontsize=11)
        ax.set_title("GNN Training Loss — CloudAutomationGNN", color="white", fontsize=13, fontweight="bold")
        ax.legend(facecolor="#1e293b", edgecolor="#334155", labelcolor="white")

        ax.set_facecolor("#0f172a")
        fig.patch.set_facecolor("#0a0e1a")
        ax.tick_params(colors="#94a3b8")
        for spine in ax.spines.values():
            spine.set_edgecolor("#334155")

        # Mark best (lowest) loss
        best_epoch = int(np.argmin(losses)) + 1
        best_val   = losses[best_epoch - 1]
        ax.axvline(best_epoch, color="#34d399", linestyle="--", linewidth=1, alpha=0.7,
                   label=f"Best epoch {best_epoch} ({best_val:.4f})")
        ax.legend(facecolor="#1e293b", edgecolor="#334155", labelcolor="white")

        plt.tight_layout()
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, dpi=150)
        plt.close()
        print(f"\n📈  Loss curve saved: {save_path}")
    except ImportError:
        print("  ⚠️  matplotlib not installed — skipping loss curve plot")
    except Exception as exc:
        print(f"  ⚠️  Plot failed: {exc}")


def main():
    set_seed(SEED)

    print("=" * 60)
    print("  CloudAutomationGNN — GraphSAGE Training")
    print("=" * 60)

    # ── 1. Load data ──────────────────────────────────────────────────────────
    data = load_data(DATA_PATH)

    # ── 2. Class weight (handle imbalanced labels) ────────────────────────────
    n_pos    = float(data.y.sum().item())
    n_neg    = float(data.y.size(0)) - n_pos
    pos_weight = torch.tensor(n_neg / (n_pos + 1e-8))
    print(f"⚖️   Class weights — normal: {int(n_neg)}, anomaly: {int(n_pos)}, "
          f"pos_weight: {pos_weight.item():.2f}")

    # ── 3. Model, optimizer, loss ─────────────────────────────────────────────
    model     = GraphSAGE(input_dim=INPUT_DIM, dropout=0.3)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=5e-4)
    criterion = nn.BCELoss()            # BCELoss — targets must be float in [0, 1]

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"🧠  Model params: {n_params:,}")
    print(f"📐  Architecture: {INPUT_DIM} → 64 → 32 → 1 (sigmoid)")
    print(f"🔧  Optimizer: Adam  lr={LR}  weight_decay=5e-4")
    print(f"📉  Loss: BCELoss  pos_weight={pos_weight.item():.2f}\n")

    # ── 4. Training loop ──────────────────────────────────────────────────────
    losses: list = []
    best_loss  = float("inf")
    best_state = None
    t_start    = time.time()

    print(f"{'Epoch':>6}  {'Loss':>10}  {'Acc':>8}  {'F1':>8}")
    print("─" * 40)

    for epoch in range(1, EPOCHS + 1):
        loss_val = train_epoch(model, data, optimizer, criterion)
        losses.append(loss_val)

        if loss_val < best_loss:
            best_loss  = loss_val
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

        if epoch % PRINT_EVERY == 0 or epoch == 1:
            acc, f1, _ = evaluate(model, data)
            print(f"{epoch:>6}  {loss_val:>10.4f}  {acc:>8.4f}  {f1:>8.4f}")

    elapsed = time.time() - t_start

    # ── 5. Restore best checkpoint ────────────────────────────────────────────
    if best_state:
        model.load_state_dict(best_state)
        print(f"\n✅  Best checkpoint restored (loss={best_loss:.4f})")

    # ── 6. Final evaluation ───────────────────────────────────────────────────
    acc, f1, scores = evaluate(model, data)
    preds  = (scores >= THRESHOLD).astype(int)
    labels = data.y.numpy()

    print("\n" + "=" * 60)
    print("  Final Evaluation (full graph)")
    print("=" * 60)
    print(f"  Accuracy : {acc:.4f}  ({acc * 100:.1f}%)")
    print(f"  F1 Score : {f1:.4f}")
    print(f"  Threshold: {THRESHOLD}")
    print(f"  Time     : {elapsed:.1f}s")

    print("\n📊  Per-node scores:")
    node_ids = getattr(data, "node_ids", [str(i) for i in range(data.num_nodes)])
    for i, (nid, score, pred, label) in enumerate(zip(node_ids, scores, preds, labels)):
        match  = "✓" if pred == label else "✗"
        marker = "🔴" if label else "🟢"
        print(f"  {match} {marker}  {nid:18s}  score={score:.4f}  pred={'ANOM' if pred else 'OK':5s}  true={'ANOM' if label else 'OK'}")

    # ── 7. Save model ─────────────────────────────────────────────────────────
    os.makedirs(MODEL_DIR, exist_ok=True)
    torch.save(model.state_dict(), MODEL_PATH)
    size_kb = os.path.getsize(MODEL_PATH) / 1024
    print(f"\n💾  Model saved: {MODEL_PATH}  ({size_kb:.1f} KB)")

    # ── 8. Plot loss curve ────────────────────────────────────────────────────
    plot_loss(losses, LOSS_PLOT)

    print("\n🎉  Training complete!\n")


if __name__ == "__main__":
    main()
